[pytest]
asyncio_mode = auto
addopts = -q
python_files = test_*.py *_test.py
python_functions = test_*
python_classes = Test*
testpaths =
    tests
    .
filterwarnings =
    ignore::pytest.PytestRemovedIn9Warning
